### ISSUE TITLE
coming out date leaked

### ISSUE THREAD

**Issue by Milxnor** [Trail-Blaze/Icarus#2]
**never**

**Comment by AlexDev404** [comment]
> **never**

@Milxnor I suggest you look into the deeper meaning of the contents of the `README.md` file before posting something as stupid as this. It just comes to show that you've read nothing at all.

**Comment by AlexDev404** [comment]
My work is methodolical and planned out. What I produce is of short supply, takes time, but is of high quality. I do not go about generating programs that have little to no structure and with no merit other than "just work" while being hard-to-read and maintain.

**Comment by AlexDev404** [comment]
So if you have nothing better to say or contribute, I suggest you go back to rebooting your [reboot project](https://github.com/Milxnor/Project-Reboot-3.0) for the third time!

**Comment by Milxnor** [comment]
> So if you have nothing better to say or contribute, I suggest you go back to rebooting your [reboot project](https://github.com/Milxnor/Project-Reboot-3.0) for the third time!

atleast i can release a project 😭
